### ISSUE TITLE
Problem to compile C3D for "make runtest"

### ISSUE THREAD

**Issue by fahimeh62** [facebook/C3D#37]
@dutran Hi. 
I have a problem when I wanted to compile C3D on my machine. I got error after "make all" that I fixed it using "https://github.com/facebook/C3D/issues/2"
but for "make runtest" I still got error. I used suggestions in "https://github.com/BVLC/caffe/issues/626", but I could not fix it. Here it is my current Makefile.config: 

![image](https://cloud.githubusercontent.com/assets/10705550/10624499/491e847e-77dc-11e5-980c-ba5fb857cffa.png)

I got this error after running make runtest:
build/test/test_all.testbin 0 --gtest_shuffle
Cuda number of devices: 1
Setting to use device 0
Current device id: 0
Note: Randomizing tests' orders with a seed of 22059 .
[==========] Running 407 tests from 72 test cases.
[----------] Global test environment set-up.
[----------] 1 test from UniformFillerTest/0, where TypeParam = float
[ RUN      ] UniformFillerTest/0.TestFill
[       OK ] UniformFillerTest/0.TestFill (144 ms)
[----------] 1 test from UniformFillerTest/0 (144 ms total)

[----------] 5 tests from Im2colLayerTest/1, where TypeParam = double
[ RUN      ] Im2colLayerTest/1.TestCPU
[       OK ] Im2colLayerTest/1.TestCPU (0 ms)
[ RUN      ] Im2colLayerTest/1.TestGPU
F1021 20:35:10.515538 22797 im2col.cu:54] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function 
*** Check failure stack trace: ***
    @     0x2b97e26b2daa  (unknown)
    @     0x2b97e26b2ce4  (unknown)
    @     0x2b97e26b26e6  (unknown)
    @     0x2b97e26b5687  (unknown)
    @           0x5d6b60  caffe::im2col_gpu<>()
    @           0x5c0127  caffe::Im2colLayer<>::Forward_gpu()
    @           0x4482e0  caffe::Layer<>::Forward()
    @           0x4b6bee  caffe::Im2colLayerTest_TestGPU_Test<>::TestBody()
    @           0x538cd3  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x52f7b7  testing::Test::Run()
    @           0x52f85e  testing::TestInfo::Run()
    @           0x52f965  testing::TestCase::Run()
    @           0x532ca8  testing::internal::UnitTestImpl::RunAllTests()
    @           0x532f37  testing::UnitTest::Run()
    @           0x412c10  main
    @     0x2b97e4c19ec5  (unknown)
    @           0x417e3e  (unknown)
    @              (nil)  (unknown)
make: *** [runtest] Aborted (core dumped)

Could you please help me to fix it.
Thanks a lot.

**Comment by dutran** [comment]
Are you running on a computer with GPU?

**Comment by fahimeh62** [comment]
@dutran yes, and I have compiled the master branch of Caffe successfully before. it did not give me this error at all. So it can not be GPU-related error. right?

**Comment by dutran** [comment]
Hi @fahimeh62 I still think your problem is about CUDA. It is either CUDA driver is not correctly install or something. You failed at a CUDA_POST_KERNEL_CHECK (https://github.com/facebook/C3D/blob/master/src/caffe/util/im2col.cu#L54)

**Comment by dutran** [comment]
If you look at its definition at (https://github.com/facebook/C3D/blob/ffccac01f3e09ccd8fec73cda647d38f816dccab/include/caffe/common.hpp#L57)
#define CUDA_POST_KERNEL_CHECK CUDA_CHECK(cudaPeekAtLastError())
It checks the last error made by CUDA.

**Comment by dutran** [comment]
@fahimeh62 have you resolved your issue?

**Comment by fahimeh62** [comment]
@dutran Sorry I forgot to say you. 
yes. I changed my makefile. I used that one that I previously used for master branch of Caffe and the problem is resolved.  
Thanks for your help.
