### ISSUE TITLE
different results produced by CPU and GPU mode

### ISSUE THREAD

**Issue by mmchen88** [facebook/C3D#420]
I use the same UCF101 model, same data ,but get different results when using CPU mode and GPU mode.

**Comment by dutran** [comment]
how much different? is it about machine epsilon? CPU and GPU may have different floating point precison.

**Comment by mmchen88** [comment]
I found the reason, CudnnReluLayer in GPU mode only process 4D tensors. When the tensor is 5D, the code must be modified.
